using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmugSharp.Models
{
    public class Album
    {
        public string ResponseLevel { get; set; }// "Full",
        public string Uri { get; set; }// "/api/v2/album/LNdnfb",
        public string WebUri { get; set; }// "http://photos.hofker.org/Photography/Other/Site-pictures/n-KdQBT",
        public string UriDescription { get; set; }// "Album by key",
        public string NiceName { get; set; }// "Site-pictures",
        public string UrlName { get; set; }// "Site-pictures",
        public string Title { get; set; }// "site-pictures",
        public string Name { get; set; }// "site-pictures",
        public string AllowDownloads { get; set; }// true,
        public string Backprinting { get; set; }// "HOFKER-PHOTOS",
        public string BoutiquePackaging { get; set; }// "Inherit from User",
        public string CanRank { get; set; }// false,
        public string Clean { get; set; }// false,
        public string Comments { get; set; }// false,
        public string Description { get; set; }// "",
        public string EXIF { get; set; }// true,
        public string External { get; set; }// true,
        public string FamilyEdit { get; set; }// false,
        public string Filenames { get; set; }// false,
        public string FriendEdit { get; set; }// false,
        public string Geography { get; set; }// true,
        public string Header { get; set; }// "Custom",
        public string HideOwner { get; set; }// false,
        public string InterceptShipping { get; set; }// "Inherit from User",
        public string Keywords { get; set; }// "",
        public string LargestSize { get; set; }// "Original",
        public string PackagingBranding { get; set; }// true,
        public string Password { get; set; }// "",
        public string PasswordHint { get; set; }// "",
        public string Printable { get; set; }// true,
        public string Privacy { get; set; }// "Unlisted",
        public string ProofDays { get; set; }// 3,
        public string Protected { get; set; }// false,
        public string Share { get; set; }// true,
        public string SmugSearchable { get; set; }// "No",
        public string SortDirection { get; set; }// "Ascending",
        public string SortMethod { get; set; }// "Position",
        public string SquareThumbs { get; set; }// true,
        public string UploadKey { get; set; }// "",
        public string Watermark { get; set; }// false,
        public string WorldSearchable { get; set; }// false,
        public string SecurityType { get; set; }// "None",
        public string AlbumKey { get; set; }// "LNdnfb",
        public string Date { get; set; }// "2010-07-12T20:11:44+00:00",
        public string LastUpdated { get; set; }// "2012-07-07T01:55:28+00:00",
        public string ImagesLastUpdated { get; set; }// "2012-07-07T02:08:31+00:00",
        public string NodeID { get; set; }// "KdQBT",
        public string OriginalSizes { get; set; }// 5233213,
        public string TotalSizes { get; set; }// 9959889,
        public string ImageCount { get; set; }// 12,
        public string UrlPath { get; set; }// "/Photography/Other/Site-pictures",
        public string CanShare { get; set; }// true,
        public string HasDownloadPassword { get; set; }// false,
    }
}
